@echo off

wav2gtsa "song1.wav"
copy mid.gta @CR.PAK\FILE0043.VAG
copy intro.gta @CR.PAK\FILE0044.VAG
copy intro.gta @CR.PAK\FILE0045.VAG
copy intro.gta @CR.PAK\FILE0046.VAG
copy outro.gta @CR.PAK\FILE0047.VAG
copy outro.gta @CR.PAK\FILE0048.VAG
copy outro.gta @CR.PAK\FILE0049.VAG

wav2gtsa "song2.wav"
copy mid.gta @CR.PAK\FILE0050.VAG
copy intro.gta @CR.PAK\FILE0051.VAG
copy intro.gta @CR.PAK\FILE0052.VAG
copy intro.gta @CR.PAK\FILE0053.VAG
copy outro.gta @CR.PAK\FILE0054.VAG
copy outro.gta @CR.PAK\FILE0055.VAG
copy outro.gta @CR.PAK\FILE0056.VAG

wav2gtsa "song3.wav"
copy mid.gta @CR.PAK\FILE0057.VAG
copy intro.gta @CR.PAK\FILE0058.VAG
copy intro.gta @CR.PAK\FILE0059.VAG
copy intro.gta @CR.PAK\FILE0060.VAG
copy outro.gta @CR.PAK\FILE0061.VAG
copy outro.gta @CR.PAK\FILE0062.VAG
copy outro.gta @CR.PAK\FILE0063.VAG

wav2gtsa "song4.wav"
copy mid.gta @CR.PAK\FILE0064.VAG
copy intro.gta @CR.PAK\FILE0065.VAG
copy intro.gta @CR.PAK\FILE0066.VAG
copy intro.gta @CR.PAK\FILE0067.VAG
copy outro.gta @CR.PAK\FILE0068.VAG
copy outro.gta @CR.PAK\FILE0069.VAG
copy outro.gta @CR.PAK\FILE0070.VAG

wav2gtsa "song5.wav"
copy mid.gta @CR.PAK\FILE0071.VAG
copy intro.gta @CR.PAK\FILE0072.VAG
copy intro.gta @CR.PAK\FILE0073.VAG
copy intro.gta @CR.PAK\FILE0074.VAG
copy outro.gta @CR.PAK\FILE0075.VAG
copy outro.gta @CR.PAK\FILE0076.VAG

wav2gtsa "song6.wav"
copy mid.gta @CR.PAK\FILE0077.VAG
copy intro.gta @CR.PAK\FILE0078.VAG
copy intro.gta @CR.PAK\FILE0079.VAG
copy intro.gta @CR.PAK\FILE0080.VAG
copy outro.gta @CR.PAK\FILE0081.VAG
copy outro.gta @CR.PAK\FILE0082.VAG
copy outro.gta @CR.PAK\FILE0083.VAG

wav2gtsa "song7.wav"
copy mid.gta @CR.PAK\FILE0084.VAG
copy intro.gta @CR.PAK\FILE0085.VAG
copy intro.gta @CR.PAK\FILE0086.VAG
copy intro.gta @CR.PAK\FILE0087.VAG
copy outro.gta @CR.PAK\FILE0088.VAG
copy outro.gta @CR.PAK\FILE0089.VAG
copy outro.gta @CR.PAK\FILE0090.VAG

wav2gtsa "song8.wav"
copy mid.gta @CR.PAK\FILE0091.VAG
copy intro.gta @CR.PAK\FILE0092.VAG
copy outro.gta @CR.PAK\FILE0093.VAG

wav2gtsa "song9.wav"
copy mid.gta @CR.PAK\FILE0094.VAG
copy intro.gta @CR.PAK\FILE0095.VAG
copy intro.gta @CR.PAK\FILE0096.VAG
copy intro.gta @CR.PAK\FILE0097.VAG
copy outro.gta @CR.PAK\FILE0098.VAG
copy outro.gta @CR.PAK\FILE0099.VAG

wav2gtsa "song10.wav"
copy mid.gta @CR.PAK\FILE0100.VAG
copy intro.gta @CR.PAK\FILE0101.VAG
copy intro.gta @CR.PAK\FILE0102.VAG
copy intro.gta @CR.PAK\FILE0103.VAG
copy outro.gta @CR.PAK\FILE0104.VAG
copy outro.gta @CR.PAK\FILE0105.VAG
copy outro.gta @CR.PAK\FILE0106.VAG

wav2gtsa "song11.wav"
copy mid.gta @CR.PAK\FILE0107.VAG
copy intro.gta @CR.PAK\FILE0108.VAG
copy intro.gta @CR.PAK\FILE0109.VAG
copy intro.gta @CR.PAK\FILE0110.VAG
copy outro.gta @CR.PAK\FILE0111.VAG
copy outro.gta @CR.PAK\FILE0112.VAG
copy outro.gta @CR.PAK\FILE0113.VAG

wav2gtsa "song12.wav"
copy mid.gta @CR.PAK\FILE0114.VAG
copy intro.gta @CR.PAK\FILE0115.VAG
copy intro.gta @CR.PAK\FILE0116.VAG
copy intro.gta @CR.PAK\FILE0117.VAG
copy outro.gta @CR.PAK\FILE0118.VAG
copy outro.gta @CR.PAK\FILE0119.VAG
copy outro.gta @CR.PAK\FILE0120.VAG

wav2gtsa "song13.wav"
copy mid.gta @CR.PAK\FILE0121.VAG
copy intro.gta @CR.PAK\FILE0122.VAG
copy intro.gta @CR.PAK\FILE0123.VAG
copy intro.gta @CR.PAK\FILE0124.VAG
copy outro.gta @CR.PAK\FILE0125.VAG
copy outro.gta @CR.PAK\FILE0126.VAG
copy outro.gta @CR.PAK\FILE0127.VAG

wav2gtsa "song14.wav"
copy mid.gta @CR.PAK\FILE0128.VAG
copy intro.gta @CR.PAK\FILE0129.VAG
copy intro.gta @CR.PAK\FILE0130.VAG
copy intro.gta @CR.PAK\FILE0131.VAG
copy outro.gta @CR.PAK\FILE0132.VAG
copy outro.gta @CR.PAK\FILE0133.VAG
copy outro.gta @CR.PAK\FILE0134.VAG

wav2gtsa "song15.wav"
copy mid.gta @CR.PAK\FILE0135.VAG
copy intro.gta @CR.PAK\FILE0136.VAG
copy intro.gta @CR.PAK\FILE0137.VAG
copy intro.gta @CR.PAK\FILE0138.VAG
copy outro.gta @CR.PAK\FILE0139.VAG
copy outro.gta @CR.PAK\FILE0140.VAG
copy outro.gta @CR.PAK\FILE0141.VAG

wav2gtsa "song16.wav"
copy mid.gta @CR.PAK\FILE0142.VAG
copy intro.gta @CR.PAK\FILE0143.VAG
copy intro.gta @CR.PAK\FILE0144.VAG
copy intro.gta @CR.PAK\FILE0145.VAG
copy outro.gta @CR.PAK\FILE0146.VAG
copy outro.gta @CR.PAK\FILE0147.VAG
copy outro.gta @CR.PAK\FILE0148.VAG

wav2gtsa "song17.wav"
copy mid.gta @CR.PAK\FILE0149.VAG
copy intro.gta @CR.PAK\FILE0150.VAG
copy intro.gta @CR.PAK\FILE0151.VAG
copy intro.gta @CR.PAK\FILE0152.VAG
copy outro.gta @CR.PAK\FILE0153.VAG
copy outro.gta @CR.PAK\FILE0154.VAG
copy outro.gta @CR.PAK\FILE0155.VAG

del mid.gta
del intro.gta
del outro.gta

exit