@echo off

wav2gtsa "song1.wav"
copy mid.gta @DS.PAK\FILE0060.VAG
copy intro.gta @DS.PAK\FILE0061.VAG
copy intro.gta @DS.PAK\FILE0062.VAG
copy intro.gta @DS.PAK\FILE0063.VAG
copy outro.gta @DS.PAK\FILE0064.VAG
copy outro.gta @DS.PAK\FILE0065.VAG
copy outro.gta @DS.PAK\FILE0066.VAG

wav2gtsa "song2.wav"
copy mid.gta @DS.PAK\FILE0067.VAG
copy intro.gta @DS.PAK\FILE0068.VAG
copy intro.gta @DS.PAK\FILE0069.VAG
copy intro.gta @DS.PAK\FILE0070.VAG
copy outro.gta @DS.PAK\FILE0071.VAG
copy outro.gta @DS.PAK\FILE0072.VAG
copy outro.gta @DS.PAK\FILE0073.VAG

wav2gtsa "song3.wav"
copy mid.gta @DS.PAK\FILE0074.VAG
copy intro.gta @DS.PAK\FILE0075.VAG
copy intro.gta @DS.PAK\FILE0076.VAG
copy intro.gta @DS.PAK\FILE0077.VAG
copy outro.gta @DS.PAK\FILE0078.VAG
copy outro.gta @DS.PAK\FILE0079.VAG
copy outro.gta @DS.PAK\FILE0080.VAG

wav2gtsa "song4.wav"
copy mid.gta @DS.PAK\FILE0081.VAG
copy intro.gta @DS.PAK\FILE0082.VAG
copy intro.gta @DS.PAK\FILE0083.VAG
copy intro.gta @DS.PAK\FILE0084.VAG
copy outro.gta @DS.PAK\FILE0085.VAG
copy outro.gta @DS.PAK\FILE0086.VAG
copy outro.gta @DS.PAK\FILE0087.VAG

wav2gtsa "song5.wav"
copy mid.gta @DS.PAK\FILE0088.VAG
copy intro.gta @DS.PAK\FILE0089.VAG
copy intro.gta @DS.PAK\FILE0090.VAG
copy intro.gta @DS.PAK\FILE0091.VAG
copy outro.gta @DS.PAK\FILE0092.VAG
copy outro.gta @DS.PAK\FILE0093.VAG
copy outro.gta @DS.PAK\FILE0094.VAG

wav2gtsa "song6.wav"
copy mid.gta @DS.PAK\FILE0095.VAG
copy intro.gta @DS.PAK\FILE0096.VAG
copy intro.gta @DS.PAK\FILE0097.VAG
copy intro.gta @DS.PAK\FILE0098.VAG
copy outro.gta @DS.PAK\FILE0099.VAG
copy outro.gta @DS.PAK\FILE0100.VAG
copy outro.gta @DS.PAK\FILE0101.VAG

wav2gtsa "song7.wav"
copy mid.gta @DS.PAK\FILE0102.VAG
copy intro.gta @DS.PAK\FILE0103.VAG
copy intro.gta @DS.PAK\FILE0104.VAG
copy intro.gta @DS.PAK\FILE0105.VAG
copy outro.gta @DS.PAK\FILE0106.VAG
copy outro.gta @DS.PAK\FILE0107.VAG
copy outro.gta @DS.PAK\FILE0108.VAG

wav2gtsa "song8.wav"
copy mid.gta @DS.PAK\FILE0109.VAG
copy intro.gta @DS.PAK\FILE0110.VAG
copy intro.gta @DS.PAK\FILE0111.VAG
copy intro.gta @DS.PAK\FILE0112.VAG
copy outro.gta @DS.PAK\FILE0113.VAG
copy outro.gta @DS.PAK\FILE0114.VAG
copy outro.gta @DS.PAK\FILE0115.VAG

wav2gtsa "song9.wav"
copy mid.gta @DS.PAK\FILE0116.VAG
copy intro.gta @DS.PAK\FILE0117.VAG
copy intro.gta @DS.PAK\FILE0118.VAG
copy intro.gta @DS.PAK\FILE0119.VAG
copy outro.gta @DS.PAK\FILE0120.VAG
copy outro.gta @DS.PAK\FILE0121.VAG
copy outro.gta @DS.PAK\FILE0122.VAG

wav2gtsa "song10.wav"
copy mid.gta @DS.PAK\FILE0123.VAG
copy intro.gta @DS.PAK\FILE0124.VAG
copy intro.gta @DS.PAK\FILE0125.VAG
copy intro.gta @DS.PAK\FILE0126.VAG
copy outro.gta @DS.PAK\FILE0127.VAG
copy outro.gta @DS.PAK\FILE0128.VAG
copy outro.gta @DS.PAK\FILE0129.VAG

wav2gtsa "song11.wav"
copy mid.gta @DS.PAK\FILE0130.VAG
copy intro.gta @DS.PAK\FILE0131.VAG
copy intro.gta @DS.PAK\FILE0132.VAG
copy intro.gta @DS.PAK\FILE0133.VAG
copy outro.gta @DS.PAK\FILE0134.VAG
copy outro.gta @DS.PAK\FILE0135.VAG
copy outro.gta @DS.PAK\FILE0136.VAG

wav2gtsa "song12.wav"
copy mid.gta @DS.PAK\FILE0137.VAG
copy intro.gta @DS.PAK\FILE0138.VAG
copy intro.gta @DS.PAK\FILE0139.VAG
copy intro.gta @DS.PAK\FILE0140.VAG
copy outro.gta @DS.PAK\FILE0141.VAG
copy outro.gta @DS.PAK\FILE0142.VAG
copy outro.gta @DS.PAK\FILE0143.VAG

wav2gtsa "song13.wav"
copy mid.gta @DS.PAK\FILE0144.VAG
copy intro.gta @DS.PAK\FILE0145.VAG
copy intro.gta @DS.PAK\FILE0146.VAG
copy intro.gta @DS.PAK\FILE0147.VAG
copy outro.gta @DS.PAK\FILE0148.VAG
copy outro.gta @DS.PAK\FILE0149.VAG
copy outro.gta @DS.PAK\FILE0150.VAG

wav2gtsa "song14.wav"
copy mid.gta @DS.PAK\FILE0151.VAG
copy intro.gta @DS.PAK\FILE0152.VAG
copy intro.gta @DS.PAK\FILE0153.VAG
copy intro.gta @DS.PAK\FILE0154.VAG
copy outro.gta @DS.PAK\FILE0155.VAG
copy outro.gta @DS.PAK\FILE0156.VAG
copy outro.gta @DS.PAK\FILE0157.VAG

wav2gtsa "song15.wav"
copy mid.gta @DS.PAK\FILE0158.VAG
copy intro.gta @DS.PAK\FILE0159.VAG
copy intro.gta @DS.PAK\FILE0160.VAG
copy intro.gta @DS.PAK\FILE0161.VAG
copy outro.gta @DS.PAK\FILE0162.VAG
copy outro.gta @DS.PAK\FILE0163.VAG
copy outro.gta @DS.PAK\FILE0164.VAG

wav2gtsa "song16.wav"
copy mid.gta @DS.PAK\FILE0165.VAG
copy intro.gta @DS.PAK\FILE0166.VAG
copy intro.gta @DS.PAK\FILE0167.VAG
copy intro.gta @DS.PAK\FILE0168.VAG
copy outro.gta @DS.PAK\FILE0169.VAG
copy outro.gta @DS.PAK\FILE0170.VAG
copy outro.gta @DS.PAK\FILE0171.VAG

wav2gtsa "song17.wav"
copy mid.gta @DS.PAK\FILE0172.VAG
copy intro.gta @DS.PAK\FILE0173.VAG
copy intro.gta @DS.PAK\FILE0174.VAG
copy intro.gta @DS.PAK\FILE0175.VAG
copy outro.gta @DS.PAK\FILE0176.VAG
copy outro.gta @DS.PAK\FILE0177.VAG
copy outro.gta @DS.PAK\FILE0178.VAG

del mid.gta
del intro.gta
del outro.gta

exit