@echo off

wav2gtsa "song1.wav"
copy mid.gta @HC.PAK\FILE0035.VAG
copy intro.gta @HC.PAK\FILE0036.VAG
copy intro.gta @HC.PAK\FILE0037.VAG
copy outro.gta @HC.PAK\FILE0038.VAG
copy outro.gta @HC.PAK\FILE0039.VAG

wav2gtsa "song2.wav"
copy mid.gta @HC.PAK\FILE0040.VAG
copy intro.gta @HC.PAK\FILE0041.VAG
copy intro.gta @HC.PAK\FILE0042.VAG
copy outro.gta @HC.PAK\FILE0043.VAG
copy outro.gta @HC.PAK\FILE0044.VAG

wav2gtsa "song3.wav"
copy mid.gta @HC.PAK\FILE0045.VAG
copy intro.gta @HC.PAK\FILE0046.VAG
copy intro.gta @HC.PAK\FILE0047.VAG
copy outro.gta @HC.PAK\FILE0048.VAG
copy outro.gta @HC.PAK\FILE0049.VAG

wav2gtsa "song4.wav"
copy mid.gta @HC.PAK\FILE0050.VAG
copy intro.gta @HC.PAK\FILE0051.VAG
copy intro.gta @HC.PAK\FILE0052.VAG
copy outro.gta @HC.PAK\FILE0053.VAG
copy outro.gta @HC.PAK\FILE0054.VAG

wav2gtsa "song5.wav"
copy mid.gta @HC.PAK\FILE0055.VAG
copy intro.gta @HC.PAK\FILE0056.VAG
copy intro.gta @HC.PAK\FILE0057.VAG
copy outro.gta @HC.PAK\FILE0058.VAG
copy outro.gta @HC.PAK\FILE0059.VAG

wav2gtsa "song6.wav"
copy mid.gta @HC.PAK\FILE0060.VAG
copy intro.gta @HC.PAK\FILE0061.VAG
copy intro.gta @HC.PAK\FILE0062.VAG
copy outro.gta @HC.PAK\FILE0063.VAG
copy outro.gta @HC.PAK\FILE0064.VAG

wav2gtsa "song7.wav"
copy mid.gta @HC.PAK\FILE0065.VAG
copy intro.gta @HC.PAK\FILE0066.VAG
copy intro.gta @HC.PAK\FILE0067.VAG
copy outro.gta @HC.PAK\FILE0068.VAG
copy outro.gta @HC.PAK\FILE0069.VAG

wav2gtsa "song8.wav"
copy mid.gta @HC.PAK\FILE0070.VAG
copy intro.gta @HC.PAK\FILE0071.VAG
copy intro.gta @HC.PAK\FILE0072.VAG
copy outro.gta @HC.PAK\FILE0073.VAG
copy outro.gta @HC.PAK\FILE0074.VAG

wav2gtsa "song9.wav"
copy mid.gta @HC.PAK\FILE0075.VAG
copy intro.gta @HC.PAK\FILE0076.VAG
copy intro.gta @HC.PAK\FILE0077.VAG
copy outro.gta @HC.PAK\FILE0078.VAG
copy outro.gta @HC.PAK\FILE0079.VAG

wav2gtsa "song10.wav"
copy mid.gta @HC.PAK\FILE0080.VAG
copy intro.gta @HC.PAK\FILE0081.VAG
copy intro.gta @HC.PAK\FILE0082.VAG
copy outro.gta @HC.PAK\FILE0083.VAG
copy outro.gta @HC.PAK\FILE0084.VAG

wav2gtsa "song11.wav"
copy mid.gta @HC.PAK\FILE0085.VAG
copy intro.gta @HC.PAK\FILE0086.VAG
copy intro.gta @HC.PAK\FILE0087.VAG
copy outro.gta @HC.PAK\FILE0088.VAG
copy outro.gta @HC.PAK\FILE0089.VAG

wav2gtsa "song12.wav"
copy mid.gta @HC.PAK\FILE0090.VAG
copy intro.gta @HC.PAK\FILE0091.VAG
copy intro.gta @HC.PAK\FILE0092.VAG
copy outro.gta @HC.PAK\FILE0093.VAG
copy outro.gta @HC.PAK\FILE0094.VAG

wav2gtsa "song13.wav"
copy mid.gta @HC.PAK\FILE0095.VAG
copy intro.gta @HC.PAK\FILE0096.VAG
copy intro.gta @HC.PAK\FILE0097.VAG
copy outro.gta @HC.PAK\FILE0098.VAG
copy outro.gta @HC.PAK\FILE0099.VAG

wav2gtsa "song14.wav"
copy mid.gta @HC.PAK\FILE0100.VAG
copy intro.gta @HC.PAK\FILE0101.VAG
copy intro.gta @HC.PAK\FILE0102.VAG
copy outro.gta @HC.PAK\FILE0103.VAG
copy outro.gta @HC.PAK\FILE0104.VAG

wav2gtsa "song15.wav"
copy mid.gta @HC.PAK\FILE0105.VAG
copy intro.gta @HC.PAK\FILE0106.VAG
copy intro.gta @HC.PAK\FILE0107.VAG
copy outro.gta @HC.PAK\FILE0108.VAG
copy outro.gta @HC.PAK\FILE0109.VAG

wav2gtsa "song16.wav"
copy mid.gta @HC.PAK\FILE0110.VAG
copy intro.gta @HC.PAK\FILE0111.VAG
copy intro.gta @HC.PAK\FILE0112.VAG
copy outro.gta @HC.PAK\FILE0113.VAG
copy outro.gta @HC.PAK\FILE0114.VAG

del mid.gta
del intro.gta
del outro.gta

exit