@echo off

wav2gtsa "song1.wav"
copy mid.gta @MR.PAK\FILE0046.VAG
copy intro.gta @MR.PAK\FILE0047.VAG
copy intro.gta @MR.PAK\FILE0048.VAG
copy intro.gta @MR.PAK\FILE0049.VAG
copy outro.gta @MR.PAK\FILE0050.VAG
copy outro.gta @MR.PAK\FILE0051.VAG
copy outro.gta @MR.PAK\FILE0052.VAG

wav2gtsa "song2.wav"
copy mid.gta @MR.PAK\FILE0053.VAG
copy intro.gta @MR.PAK\FILE0054.VAG
copy intro.gta @MR.PAK\FILE0055.VAG
copy intro.gta @MR.PAK\FILE0056.VAG
copy outro.gta @MR.PAK\FILE0057.VAG
copy outro.gta @MR.PAK\FILE0058.VAG
copy outro.gta @MR.PAK\FILE0059.VAG

wav2gtsa "song3.wav"
copy mid.gta @MR.PAK\FILE0060.VAG
copy intro.gta @MR.PAK\FILE0061.VAG
copy intro.gta @MR.PAK\FILE0062.VAG
copy intro.gta @MR.PAK\FILE0063.VAG
copy outro.gta @MR.PAK\FILE0064.VAG
copy outro.gta @MR.PAK\FILE0065.VAG
copy outro.gta @MR.PAK\FILE0066.VAG

wav2gtsa "song4.wav"
copy mid.gta @MR.PAK\FILE0067.VAG
copy intro.gta @MR.PAK\FILE0068.VAG
copy intro.gta @MR.PAK\FILE0069.VAG
copy intro.gta @MR.PAK\FILE0070.VAG
copy outro.gta @MR.PAK\FILE0071.VAG
copy outro.gta @MR.PAK\FILE0072.VAG
copy outro.gta @MR.PAK\FILE0073.VAG

wav2gtsa "song5.wav"
copy mid.gta @MR.PAK\FILE0074.VAG
copy intro.gta @MR.PAK\FILE0075.VAG
copy intro.gta @MR.PAK\FILE0076.VAG
copy intro.gta @MR.PAK\FILE0077.VAG
copy outro.gta @MR.PAK\FILE0078.VAG
copy outro.gta @MR.PAK\FILE0079.VAG
copy outro.gta @MR.PAK\FILE0080.VAG

wav2gtsa "song6.wav"
copy mid.gta @MR.PAK\FILE0081.VAG
copy intro.gta @MR.PAK\FILE0082.VAG
copy intro.gta @MR.PAK\FILE0083.VAG
copy intro.gta @MR.PAK\FILE0084.VAG
copy outro.gta @MR.PAK\FILE0085.VAG
copy outro.gta @MR.PAK\FILE0086.VAG
copy outro.gta @MR.PAK\FILE0087.VAG

wav2gtsa "song7.wav"
copy mid.gta @MR.PAK\FILE0088.VAG
copy intro.gta @MR.PAK\FILE0089.VAG
copy intro.gta @MR.PAK\FILE0090.VAG
copy intro.gta @MR.PAK\FILE0091.VAG
copy outro.gta @MR.PAK\FILE0092.VAG
copy outro.gta @MR.PAK\FILE0093.VAG
copy outro.gta @MR.PAK\FILE0094.VAG

wav2gtsa "song8.wav"
copy mid.gta @MR.PAK\FILE0095.VAG
copy intro.gta @MR.PAK\FILE0096.VAG
copy intro.gta @MR.PAK\FILE0097.VAG
copy intro.gta @MR.PAK\FILE0098.VAG
copy outro.gta @MR.PAK\FILE0099.VAG
copy outro.gta @MR.PAK\FILE0100.VAG
copy outro.gta @MR.PAK\FILE0101.VAG

wav2gtsa "song9.wav"
copy mid.gta @MR.PAK\FILE0102.VAG
copy intro.gta @MR.PAK\FILE0103.VAG
copy intro.gta @MR.PAK\FILE0104.VAG
copy intro.gta @MR.PAK\FILE0105.VAG
copy outro.gta @MR.PAK\FILE0106.VAG
copy outro.gta @MR.PAK\FILE0107.VAG
copy outro.gta @MR.PAK\FILE0108.VAG

wav2gtsa "song10.wav"
copy mid.gta @MR.PAK\FILE0109.VAG
copy intro.gta @MR.PAK\FILE0110.VAG
copy intro.gta @MR.PAK\FILE0111.VAG
copy intro.gta @MR.PAK\FILE0112.VAG
copy outro.gta @MR.PAK\FILE0113.VAG
copy outro.gta @MR.PAK\FILE0114.VAG
copy outro.gta @MR.PAK\FILE0115.VAG

wav2gtsa "song11.wav"
copy mid.gta @MR.PAK\FILE0116.VAG
copy intro.gta @MR.PAK\FILE0117.VAG
copy intro.gta @MR.PAK\FILE0118.VAG
copy intro.gta @MR.PAK\FILE0119.VAG
copy outro.gta @MR.PAK\FILE0120.VAG
copy outro.gta @MR.PAK\FILE0121.VAG
copy outro.gta @MR.PAK\FILE0122.VAG

wav2gtsa "song12.wav"
copy mid.gta @MR.PAK\FILE0123.VAG
copy intro.gta @MR.PAK\FILE0124.VAG
copy intro.gta @MR.PAK\FILE0125.VAG
copy intro.gta @MR.PAK\FILE0126.VAG
copy outro.gta @MR.PAK\FILE0127.VAG
copy outro.gta @MR.PAK\FILE0128.VAG
copy outro.gta @MR.PAK\FILE0129.VAG

wav2gtsa "song13.wav"
copy mid.gta @MR.PAK\FILE0130.VAG
copy intro.gta @MR.PAK\FILE0131.VAG
copy intro.gta @MR.PAK\FILE0132.VAG
copy intro.gta @MR.PAK\FILE0133.VAG
copy outro.gta @MR.PAK\FILE0134.VAG
copy outro.gta @MR.PAK\FILE0135.VAG
copy outro.gta @MR.PAK\FILE0136.VAG

wav2gtsa "song14.wav"
copy mid.gta @MR.PAK\FILE0137.VAG
copy intro.gta @MR.PAK\FILE0138.VAG
copy intro.gta @MR.PAK\FILE0139.VAG
copy intro.gta @MR.PAK\FILE0140.VAG
copy outro.gta @MR.PAK\FILE0141.VAG
copy outro.gta @MR.PAK\FILE0142.VAG
copy outro.gta @MR.PAK\FILE0143.VAG

wav2gtsa "song15.wav"
copy mid.gta @MR.PAK\FILE0144.VAG
copy intro.gta @MR.PAK\FILE0145.VAG
copy outro.gta @MR.PAK\FILE0146.VAG

del mid.gta
del intro.gta
del outro.gta

exit